<?php
return [
		//0
		[
				'text'=>'商品详情',
				'icon'=>null,
				'index'=>'GoodsDetails'
		],
		//1
		[
				'text'=>'商品分类',
				'icon'=>null,
				'index'=>'Category'
		],
		//2
		[
				'text'=>'商品规格',
				'icon'=>null,
				'index'=>'GoodsSpecs'
		],
		//3
		[
				'text'=>'商品类型',
				'icon'=>null,
				'index'=>'GoodsType'
		],
		//4
		[
				'text'=>'组织单位',
				'icon'=>null,
				'index'=>'Department'
		],
		//5
		[
				'text'=>'团队小组',
				'icon'=>null,
				'index'=>'Group',
		],
		//6
		[
				'text'=>'员工信息',
				'icon'=>null,
				'index'=>'Employee'
		],
		//7
		[
				'text'=>'保证金',
				'icon'=>null,
				'index'=>'Deposit'
		],
		//8
		[
				'text'=>'客户资料',
				'icon'=>null,
				'index'=>'Customer'
		],
		//9
		[
				'text'=>'订单详情',
				'icon'=>null,
				'index'=>'OrderList'
		],
		//10
		[
				'text'=>'订单审核',
				'icon'=>null,
				'index'=>'BuyOrders'
		],
		//11
		[
				'text'=>'退款审核',
				'icon'=>null,
				'index'=>'Refund'
		],
		//12
		[
				'text'=>'库存详情',
				'icon'=>null,
				'index'=>'InventoryList'
		],
		//13
		[
				'text'=>'库存日志（未实现）',
				'icon'=>null,
				'index'=>''
		],
		//14
		[
				'text'=>'物流信息',
				'icon'=>null,
				'index'=>'ExpressInfo'
		],
		//15
		[
				'text'=>'最新资讯',
				'icon'=>null,
				'index'=>'Articles'
		],
		//16
		[
				'text'=>'资讯详情',
				'icon'=>null,
				'index'=>'SkinCareInfo'
		],
		//17
		[
				'text'=>'留言详情',
				'icon'=>null,
				'index'=>'Connection'
		],
        //18
        [
            'text'=>'我的工作台',
            'icon'=>null,
            'index'=>'Workbench'
        ],
        //19
        [
            'text'=>'系统公告',
            'icon'=>null,
            'index'=>'SysNotice'
        ],
        //20
        [
            'text'=>'重要联系人',
            'icon'=>null,
            'index'=>'Contacts'
        ],
        //21
        [
            'text'=>'常用网址',
            'icon'=>null,
            'index'=>'Website'
        ],
        
		
];